import '../env'

export default {
  GCLOUD_PROJECT: process.env.GCLOUD_PROJECT,
  GOOGLE_APPLICATION_CREDENTIALS: process.env.GOOGLE_APPLICATION_CREDENTIALS,
  SPREAD_SHEET_ID: process.env.SPREAD_SHEET_ID
}
